name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 1 * *" # monthly

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

  checks:
    name: Checks
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run checks
        run: ./scripts/checks.nu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  coverage:
    name: Coverage
    needs: setup
    runs-on: ubuntu-24.04
    permissions:
      id-token: write # codecov
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

      - name: Generate coverage
        run: ./scripts/coverage.nu

      - name: Upload coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: coverage/coverage-final.json
          fail_ci_if_error: true
          use_oidc: true
