name: Integration

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  cold:
    name: Cold / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0

      - name: Cache
        id: cache
        uses: ./
        with:
          key: integration-${{ matrix.os }}-${{ github.sha }}

      - name: Miss
        shell: bash
        env:
          CACHE_HIT: ${{ steps.cache.outputs.cache-hit }}
        run: |
          if [[ "${CACHE_HIT}" == "true" ]]; then
            echo "Expected miss"
            exit 1
          fi

      - name: Build
        run: nix develop ./tests/integration --command true

  warm:
    name: Warm / ${{ matrix.os }}
    needs: cold
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0

      - name: Cache
        id: cache
        uses: ./
        with:
          key: integration-${{ matrix.os }}-${{ github.sha }}

      - name: Hit
        shell: bash
        env:
          CACHE_HIT: ${{ steps.cache.outputs.cache-hit }}
        run: |
          if [[ "${CACHE_HIT}" != "true" ]]; then
            echo "Expected hit"
            exit 1
          fi

      - name: Build
        run: nix develop ./tests/integration --command true
